spring.application.name=ingestor-service
# 1. Define a logical name 'news-out-0' and map it to a Kafka topic
spring.cloud.stream.bindings.news-out-0.destination=raw-news-topic

# 2. Tell Spring where to find Kafka (localhost:9092 because the app runs on your Mac)
spring.kafka.bootstrap-servers=localhost:9092